import { useState } from 'react'
import { Link } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowDown, ArrowUpRight, X } from 'lucide-react'
import { sectors } from '../data/sectors'
import { Header, Footer, SocialDock } from '../components/Layout'
import Reveal from '../components/Reveal'

export default function Home(){const [active,setActive]=useState(null);const sector=sectors.find(s=>s.slug===active);return <main><Header/><SocialDock/><section className="hero"><motion.div className="hero-intro" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.6,ease:[.16,1,.3,1]}}><h1>Clean what blocks.<br/><em>Elevate what moves.</em></h1><a className="scroll-cue" href="#sectors"><span>Explore our services</span><ArrowDown size={16}/></a></motion.div><div className="hero-orbit" aria-hidden="true"><i/><i/><i/></div></section><section id="sectors" className="sectors"><div className="section-head"><p className="eyebrow">What SAMFI does</p><p>Four ways to<br/>clean and elevate.</p></div><div className="sector-grid">{sectors.map((s,i)=>{const Icon=s.icon;return <motion.button type="button" initial={{opacity:0,y:45}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:i*.12,duration:.7,ease:[.16,1,.3,1]}} key={s.slug} className={`sector-wrap ${s.color}`} onClick={()=>setActive(s.slug)}><span className="sector-card"><span className="card-top"><span>{s.number}</span><Icon size={21}/></span><span className="card-content"><span>{s.label}</span><h2>{s.title}</h2><span className="card-reveal"><span>{s.short}</span><ArrowUpRight size={20}/></span></span></span></motion.button>})}</div></section><section className="manifesto"><Reveal><p className="eyebrow">The SAMFI approach</p><h2>Clear the noise.<br/><em>Raise the standard.</em></h2></Reveal><Reveal className="manifesto-copy"><p>“Clean and elevate” is our way of working: remove what prevents progress, then strengthen what helps people and organisations flourish.</p><Link to="/empowerment">How we work <ArrowUpRight size={17}/></Link></Reveal></section><section className="principles"><Reveal><p className="eyebrow">Built around what lasts</p></Reveal><div>{[['01','Clarity before action'],['02','Progress with proof'],['03','Capability, not dependency']].map(([n,t])=><Reveal key={n} className="principle"><span>{n}</span><h3>{t}</h3></Reveal>)}</div></section><Footer/><AnimatePresence>{sector&&<motion.div className="sector-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)}><motion.article className={`sector-modal ${sector.color}`} initial={{y:35,opacity:0}} animate={{y:0,opacity:1}} exit={{y:25,opacity:0}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setActive(null)} aria-label="Close"><X size={20}/></button><p className="eyebrow">{sector.number} · {sector.label}</p><h2>{sector.title}</h2><p>{sector.preview}</p><Link to={sector.slug} className="modal-link" onClick={()=>setActive(null)}>More details <ArrowUpRight size={18}/></Link></motion.article></motion.div>}</AnimatePresence></main>}
